services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=posts_app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
